import { getRandomPrice } from './utils';

export enum TagEnum {
  filosofico = 'Filosofico',
  buffo = 'Buffo',
}

export type Tag = keyof typeof TagEnum;

export class Listing {
  id: string;
  name: string;
  price: number;
  tags: TagEnum[];

  constructor(id: string, name: string, price: number, tags: TagEnum[] = []) {
    this.id = id;
    this.name = name;
    this.price = price;
    this.tags = tags;
  }
}

export const calendariFilosofici: Listing[] = [
  new Listing('aristotele', 'Calendario di Aristotele', getRandomPrice(10, 100)),
  new Listing('platone', 'Calendario di Platone', getRandomPrice(10, 100)),
  new Listing('socrate', 'Calendario di Socrate', getRandomPrice(10, 100)),
  new Listing('epicuro', 'Calendario di Epicuro', getRandomPrice(10, 100)),
  new Listing('zenone', 'Calendario di Zenone', getRandomPrice(10, 100)),
  new Listing('eraclito', 'Calendario di Eraclito', getRandomPrice(10, 100)),
  new Listing('parmenide', 'Calendario di Parmenide', getRandomPrice(10, 100)),
  new Listing('anassimandro', 'Calendario di Anassimandro', getRandomPrice(10, 100)),
  new Listing('pitagora', 'Calendario di Pitagora', getRandomPrice(10, 100)),
  new Listing('talete', 'Calendario di Talete', getRandomPrice(10, 100)),
  new Listing('anassagora', 'Calendario di Anassagora', getRandomPrice(10, 100)),
  new Listing('democrito', 'Calendario di Democrito', getRandomPrice(10, 100)),
  new Listing('empedocle', 'Calendario di Empedocle', getRandomPrice(10, 100)),
  new Listing('gorgia', 'Calendario di Gorgia', getRandomPrice(10, 100)),
  new Listing('protagora', 'Calendario di Protagora', getRandomPrice(10, 100)),
  new Listing('diogene', 'Calendario di Diogene', getRandomPrice(10, 100)),
  new Listing('cratilo', 'Calendario di Cratilo', getRandomPrice(10, 100)),
  new Listing('pirrone', 'Calendario di Pirrone', getRandomPrice(10, 100)),
  new Listing('plotino', 'Calendario di Plotino', getRandomPrice(10, 100)),
  new Listing('porfirio', 'Calendario di Porfirio', getRandomPrice(10, 100)),
  new Listing('giamblico', 'Calendario di Giamblico', getRandomPrice(10, 100)),
  new Listing('proclo', 'Calendario di Proclo', getRandomPrice(10, 100)),
  new Listing('anselmo', 'Calendario di Anselmo', getRandomPrice(10, 100)),
  new Listing('agostino', 'Calendario di Agostino', getRandomPrice(10, 100)),
  new Listing('tomaso_daquino', "Calendario di Tommaso d'Aquino", getRandomPrice(10, 100)),
  new Listing('abelardo', 'Calendario di Abelardo', getRandomPrice(10, 100)),
  new Listing('ockham', 'Calendario di Ockham', getRandomPrice(10, 100)),
  new Listing('duns_scoto', 'Calendario di Duns Scoto', getRandomPrice(10, 100)),
  new Listing('roscellino', 'Calendario di Roscellino', getRandomPrice(10, 100)),
  new Listing('machiavelli', 'Calendario di Machiavelli', getRandomPrice(10, 100)),
  new Listing('hobbes', 'Calendario di Hobbes', getRandomPrice(10, 100)),
  new Listing('spinoza', 'Calendario di Spinoza', getRandomPrice(10, 100)),
  new Listing('locke', 'Calendario di Locke', getRandomPrice(10, 100)),
  new Listing('leibniz', 'Calendario di Leibniz', getRandomPrice(10, 100)),
  new Listing('berkeley', 'Calendario di Berkeley', getRandomPrice(10, 100)),
  new Listing('hume', 'Calendario di Hume', getRandomPrice(10, 100)),
  new Listing('kant', 'Calendario di Kant', getRandomPrice(10, 100)),
  new Listing('fichte', 'Calendario di Fichte', getRandomPrice(10, 100)),
  new Listing('schelling', 'Calendario di Schelling', getRandomPrice(10, 100)),
  new Listing('hegel', 'Calendario di Hegel', getRandomPrice(10, 100)),
  new Listing('schopenhauer', 'Calendario di Schopenhauer', getRandomPrice(10, 100)),
  new Listing('kierkegaard', 'Calendario di Kierkegaard', getRandomPrice(10, 100)),
  new Listing('marx', 'Calendario di Marx', getRandomPrice(10, 100)),
  new Listing('nietzsche', 'Calendario di Nietzsche', getRandomPrice(10, 100)),
  new Listing('husserl', 'Calendario di Husserl', getRandomPrice(10, 100)),
  new Listing('heidegger', 'Calendario di Heidegger', getRandomPrice(10, 100)),
  new Listing('sartre', 'Calendario di Sartre', getRandomPrice(10, 100)),
  new Listing('camus', 'Calendario di Camus', getRandomPrice(10, 100)),
  new Listing('merleau-ponty', 'Calendario di Merleau-Ponty', getRandomPrice(10, 100)),
  new Listing('levnias', 'Calendario di Levinas', getRandomPrice(10, 100)),
  new Listing('deleuze', 'Calendario di Deleuze', getRandomPrice(10, 100)),
  new Listing('foucault', 'Calendario di Foucault', getRandomPrice(10, 100)),
  new Listing('derrida', 'Calendario di Derrida', getRandomPrice(10, 100)),
  new Listing('adorno', 'Calendario di Adorno', getRandomPrice(10, 100)),
  new Listing('Horkheimer', 'Calendario di Horkheimer', getRandomPrice(10, 100)),
  new Listing('marcuse', 'Calendario di Marcuse', getRandomPrice(10, 100)),
  new Listing('habermas', 'Calendario di Habermas', getRandomPrice(10, 100)),
  new Listing('popper', 'Calendario di Popper', getRandomPrice(10, 100)),
  new Listing('kuhn', 'Calendario di Kuhn', getRandomPrice(10, 100)),
  new Listing('feyerabend', 'Calendario di Feyerabend', getRandomPrice(10, 100)),
  new Listing('rawls', 'Calendario di Rawls', getRandomPrice(10, 100)),
  new Listing('nozick', 'Calendario di Nozick', getRandomPrice(10, 100)),
  new Listing('rorty', 'Calendario di Rorty', getRandomPrice(10, 100)),
  new Listing('putnam', 'Calendario di Putnam', getRandomPrice(10, 100)),
  new Listing('quine', 'Calendario di Quine', getRandomPrice(10, 100)),
  new Listing('Kripke', 'Calendario di Kripke', getRandomPrice(10, 100)),
  new Listing('Davidson', 'Calendario di Davidson', getRandomPrice(10, 100)),
  new Listing('Anscombe', 'Calendario di Anscombe', getRandomPrice(10, 100)),
  new Listing('MacIntyre', 'Calendario di MacIntyre', getRandomPrice(10, 100)),
  new Listing('Ricoeur', 'Calendario di Ricoeur', getRandomPrice(10, 100)),
  new Listing('Taylor', 'Calendario di Taylor', getRandomPrice(10, 100)),
  new Listing('Nussbaum', 'Calendario di Nussbaum', getRandomPrice(10, 100)),
  new Listing('Sandel', 'Calendario di Sandel', getRandomPrice(10, 100)),
  new Listing('Nagel', 'Calendario di Nagel', getRandomPrice(10, 100)),
  new Listing('Chalmers', 'Calendario di Chalmers', getRandomPrice(10, 100)),
  new Listing('Dennett', 'Calendario di Dennett', getRandomPrice(10, 100)),
  new Listing('Searle', 'Calendario di Searle', getRandomPrice(10, 100)),
  new Listing('Churchland', 'Calendario di Churchland', getRandomPrice(10, 100)),
  new Listing('Harman', 'Calendario di Harman', getRandomPrice(10, 100)),
  new Listing('Plantinga', 'Calendario di Plantinga', getRandomPrice(10, 100)),
  new Listing('Van Inwagen', 'Calendario di Van Inwagen', getRandomPrice(10, 100)),
  new Listing('Williamson', 'Calendario di Williamson', getRandomPrice(10, 100)),
  new Listing('Vattimo', 'Calendario di Vattimo', getRandomPrice(10, 100)),
  new Listing('Gadamer', 'Calendario di Gadamer', getRandomPrice(10, 100)),
  new Listing('Ricoeur', 'Calendario di Ricoeur', getRandomPrice(10, 100)),
  new Listing('Badiou', 'Calendario di Badiou', getRandomPrice(10, 100)),
  new Listing('Agamben', 'Calendario di Agamben', getRandomPrice(10, 100)),
  new Listing('Butler', 'Calendario di Butler', getRandomPrice(10, 100)),
  new Listing('Rancière', 'Calendario di Rancière', getRandomPrice(10, 100)),
  new Listing('Nancy', 'Calendario di Nancy', getRandomPrice(10, 100)),
  new Listing('Sloterdijk', 'Calendario di Sloterdijk', getRandomPrice(10, 100)),
  new Listing('Bauman', 'Calendario di Bauman', getRandomPrice(10, 100)),
  new Listing('Han', 'Calendario di Han', getRandomPrice(10, 100)),
  new Listing('Latour', 'Calendario di Latour', getRandomPrice(10, 100)),
  new Listing('Harman', 'Calendario di Harman', getRandomPrice(10, 100)),
  new Listing('Morton', 'Calendario di Morton', getRandomPrice(10, 100)),
  new Listing('Meillassoux', 'Calendario di Meillassoux', getRandomPrice(10, 100)),
  new Listing('Brassier', 'Calendario di Brassier', getRandomPrice(10, 100)),
  new Listing('Boghossian', 'Calendario di Boghossian', getRandomPrice(10, 100)),
  new Listing('Sokal', 'Calendario di Sokal', getRandomPrice(10, 100)),
];
